accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
]

naver_project/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('view_page/', include('view_page.urls', namespace='view_page')),
]

view_page/urls.py
from django.urls import path

from view_page import views

app_name = 'view_page'

urlpatterns = [
    # path('list_logs/', views.listlogs, name='list_logs'),
    # path('list_logs/(?P<dpt>[-\w]+)', views.listlogs.as_view(), name='list_logs'),
    path('list_logs/', views.listlogs.as_view(), name='list_logs'),
    # path('<dpt>', views.listlogs.as_view(), name='list_logs'),
    # path('list_logs/', views.listlogs.as_view(), name='list_logs'),
    # path('list_logs/', views.listlogs.as_view(), name='list_logs'),
    path('export/csv/', views.export_sales_csv, name='export_sales_csv'),
]

accounts/models.py
from django.db import models
from django.contrib import auth

from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser, PermissionsMixin)
from django.contrib.auth import get_user_model

# Create your models here.

# class User(auth.models.User, auth.models.PermissionsMixin):
#     def __str__(self):
#         return "@{}".format(self.username)


class UserManager(BaseUserManager):
    def create_user(self, dpt, dpt_code, password=None):
        if not dpt:
            raise ValueError('Users must have an id')

        user = self.model(
            dpt= dpt,
            dpt_code=dpt_code,
        )
        user.set_password(password)
        user.is_admin = False
        user.is_active = True
        user.save(using=self._db)
        return user

    def create_superuser(self, dpt, dpt_code, password):
        user = self.create_user(
            dpt = dpt,
            password=password,
            dpt_code=dpt_code,
        )
        user.is_admin = True
        user.is_active = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser,PermissionsMixin):
    dpt = models.CharField(
        verbose_name='dpt',
        max_length=255,
        unique=True,
        default= ''
    )
    dpt_code = models.CharField(max_length=255,unique=False, default = '')
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'dpt'
    REQUIRED_FIELDS = ['dpt_code']

    def __str__(self):
        return self.dpt

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

groups/models.py
from django.db import models

# Create your models here.


from django.contrib.auth import get_user_model
User = get_user_model() # This allows you to get the current user logged into a session.


class Group(models.Model):
    dpt_code = models.CharField(max_length=255, unique= True, default = '')
    dpt_name = models.CharField(max_length=255, unique=True, default = '')

    def __str__(self):
        return self.dpt_name

    class Meta:
        ordering = ['dpt_code']

view_page/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.timezone import now
from django.db import models

from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model() # This allows you to get the current user logged into a session.


# Create your models here.

class Log(models.Model):

    group = models.ForeignKey(Group, related_name='view_page', on_delete=models.CASCADE, default = '')
    user = models.ForeignKey(User, related_name='view_page', on_delete=models.CASCADE, default = '')

    log_date = models.DateTimeField(default=now)
    log_time = models.DateTimeField(default=now)
    log_userid = models.CharField(max_length=60)
    log_question = models.TextField(default='질문')
    log_answer = models.TextField(default='답변')

    def __str__(self):
        return self.log_question

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import User

class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('dpt', 'dpt_code')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):


        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('dpt', 'password', 'dpt_code', 'is_active', 'is_admin')

    def clean_password(self):
        return self.initial["password"]

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView

groups/views.py
from django.shortcuts import render

# Create your views here.

naver_project/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

view_page/views.py
from __future__ import unicode_literals

import csv

from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from .models import Log

# Exporting csv files
User = get_user_model()

from django.views import generic

from . import models


# Create your views here.

class listlogs(generic.ListView):
    model = models.Log
    print("LOADING MODEL ?")
    template_name = 'view_page/list_logs.html'

    def get_queryset(self):
        try:
            user = self.request.user

            self.search_keyword = self.request.GET.get('search_keyword')
            self.from_date = self.request.GET.get('from_date')
            self.to_date = self.request.GET.get('to_date')

            if self.to_date is None:
                self.to_date = '2999-01-01'
            if self.from_date is None:
                self.from_date = '2010-01-01'
            if self.search_keyword is None:
                self.search_keyword = ""

            self.log_user = User.objects.all()

        except:
            print("Replace this line with raise Http404")
        else:
            print("ABOUT to FAIL")

            # print("DDD", self.get('dpt'))

            print("THIS IS IT1", self.kwargs.get('dpt'))
            self.log_user = User.objects.prefetch_related('view_page').get(dpt__iexact=user.dpt)
            # self.log_user = User.objects.prefetch_related('view_page').get(dpt__iexact=self.kwargs.get('dpt'))

            print("THIS IS IT2", self.log_user)
            print("OMG IM GONNA CRY", self.log_user.view_page.all())

            return self.log_user.view_page.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['log_user'] = self.log_user
        context['to_date'] = self.to_date
        context['from_date'] = self.from_date
        context['search_keyword'] = self.search_keyword
        return context


@csrf_exempt
def export_sales_csv(request):
    to_date = request.GET.get('to_date')
    from_date = request.GET.get('from_date')
    # $('.date').val()

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="log.csv"'
    writer = csv.writer(response)
    writer.writerow(['A', 'B', 'C', 'D', 'E'])
    log_list = Log.objects.all().values_list('id', 'log_date', 'log_time', 'log_userid', 'log_question', 'log_answer') \
        .filter(log_date__range=[from_date, to_date], log_userid='a')
    for log in log_list:
        writer.writerow(log)
    return response

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>LOTTE NAVER</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

      <script type="text/javascript" src="/static/jquery-3.2.1.min.js"></script>
      <link rel="stylesheet" href="/static/css/bootstrap.css">

  </head>


  <body>
  <style type="text/css">
    .tg  {border-collapse:collapse;border-spacing:0;}
    .tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
    .tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
    .tg .tg-21xh{font-weight:bold;background-color:#D3D3D3;color:#333333;border-color:inherit;text-align:left;vertical-align:top}
    .tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
    .content_wrap {width: 80%; margin: 0 auto;}
    .pagination  {text-align: center; width: 100%;}
  </style>

  <script type="text/javascript" src="/static/bootstrap.js"></script>
  <script type="text/javascript" src="/static/jquery.bootstrap.modal.forms.js"></script>
  <link href="/static/css/bootstrap-datepicker.css" rel="stylesheet" />
  <script type="text/javascript" src="/static/moment-with-locales.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap-datepicker.js"></script>

    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            </div>
        </div>
    </div>


    <nav class="navbar  mynav" role="navigation" id="navbar">
        <div class="container">
            <a class="navbar-brand mynav" href="{% url 'home' %}">NAVER SMARTSTORE</a>


            <a href="{% url 'view_page:list_logs' %}">COMEON! {{log_user.dpt}} </a>



            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container mycontent">
        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>WELCOME</h1>
{% endblock %}

view_page/templates/view_page/list_logs.html
{% extends 'base.html' %}

{% block content %}


<div class="content_wrap">

<form action="/view_page/list_logs/" method="get">
    {% csrf_token %}
    <fieldset>
        <label> 기간 : </label>
        <input id="fromDate" data-provide="datepicker" data-date-format="yyyy-mm-dd" name="from_date" value="{{ from_date }}" formaction="/view_page/export_sales_csv/" />
        <label> ~ </label>
        <input id="toDate" data-provide="datepicker" data-date-format="yyyy-mm-dd" name="to_date" value="{{ to_date }}" formaction="/view_page/export_sales_csv/" />
        <label>검색어
            <input type="text" name="search_keyword" value="{{ keyword }}" formaction="/view_page/export_sales_csv/" />
        </label>
        <button type="submit">검색</button>
    </fieldset>

</form>

    <table class = "tg">
        <colgroup>
            <col width="10%">
            <col width="10%">
            <col width="10%">
            <col width="35%">
            <col width="35%">
        </colgroup>

        <tr>
            <th class="tg-21xh"> DATE </th>
            <th class="tg-21xh"> TIME </th>
            <th class="tg-21xh"> USER_ID </th>
            <th class="tg-21xh"> Q </th>
            <th class="tg-21xh"> A </th>
        </tr>

        {%  for log in log_list %}
        <tr>
            <td>{{ log.log_date }}</td>
            <td>{{ log.log_time }}</td>
            <td>{{ log.log_userid }}</td>
            <td>{{ log.log_question }}</td>
            <td>{{ log.log_answer }}</td>
        </tr>
        {% endfor %}
    </table>

</div>

{% endblock %}

view_page/templates/view_page/list_logs_temp.html
{% extends 'base.html' %}

{% block content %}


<div class="content_wrap">

<form action="/view_page/list_logs/" method="get">
    {% csrf_token %}
    <fieldset>
        <label> 기간 : </label>
        <input id="fromDate" data-provide="datepicker" data-date-format="yyyy-mm-dd" name="from_date" value="{{ from_date }}" formaction="/view_page/export_sales_csv/" />
        <label> ~ </label>
        <input id="toDate" data-provide="datepicker" data-date-format="yyyy-mm-dd" name="to_date" value="{{ to_date }}" formaction="/view_page/export_sales_csv/" />
        <label>검색어
            <input type="text" name="search_keyword" value="{{ keyword }}" formaction="/view_page/export_sales_csv/" />
        </label>
        <button type="submit">검색</button>
    </fieldset>

</form>

    <table class = "tg">
        <colgroup>
            <col width="10%">
            <col width="10%">
            <col width="10%">
            <col width="35%">
            <col width="35%">
        </colgroup>

        <tr>
            <th class="tg-21xh"> DATE </th>
            <th class="tg-21xh"> TIME </th>
            <th class="tg-21xh"> USER_ID </th>
            <th class="tg-21xh"> Q </th>
            <th class="tg-21xh"> A </th>
        </tr>

        {%  for log in log_list %}
        <tr>
            <td>{{ log.log_date }}</td>
            <td>{{ log.log_date }}</td>
            <td>{{ log.log_time }}</td>
            <td>{{ log.log_userid }}</td>
            <td>{{ log.log_question }}</td>
            <td>{{ log.log_answer }}</td>
        </tr>
        {% endfor %}
    </table>

    <div class="pagination">
        <span class="step-links">
            {% if logs.has_previous %}
                <a href="?page=1&search_type={{ type }}&search_keyword={{ keyword }}">&laquo; first</a>
                <a href="?page={{ logs.previous_page_number }}&search_type={{ type }}&search_keyword={{ keyword }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ logs.number }} of {{ logs.paginator.num_pages }}.
            </span>

            {% if logs.has_next %}
                <a href="?page={{ logs.next_page_number }}&search_type={{ type }}&search_keyword={{ keyword }}">next</a>
                <a href="?page={{ logs.paginator.num_pages }}&search_type={{ type }}&search_keyword={{ keyword }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

{% endblock %}